- hosts: localhost
  vars:
    homebrew_taps:
      - Homebrew/bundle
    dotfiles_files:
      - .ackrc
      - .bin
      - .colordiffrc
      - .config
      - .gitignore
      - .gitignore_global
      - .nvimrc
      - .tmux.conf
      - Brewfile

  tasks:
    - include_vars: secrets.yml
    - include: tasks/homebrew.yml
    - include: tasks/dotfiles.yml
    - include: tasks/fish.yml
    - include: tasks/vim.yml
