- hosts: localhost
  vars:
    homebrew_packages:
      - ack
      - mas
    homebrew_taps:
      - caskroom/cask
    homebrew_cask_apps:
      - google-chrome
      - spotify
      - omnifocus
    app_store_apps:
      # Airmail 3
      - 918858936
      # Dash 3
      - 449589707
    dotfiles_files:
      - .ackrc
      - .bin
      - .colordiffrc
      - .config
      - .git
      - .gitignore
      - .gitignore_global
      - .nvimrc
      - .tmux.conf



  tasks:
    - include: tasks/homebrew.yml
    - include: tasks/mas.yml
    - include: tasks/dotfiles.yml
