- hosts: localhost
  vars:
    homebrew_taps:
      - Homebrew/bundle
    dotfiles_files:
      - .ackrc
      - .bin
      - .colordiffrc
      - .config
      - .gitignore
      - .gitignore_global
      - .nvimrc
      - .tmux.conf
      - Brewfile



  tasks:
    - include: tasks/homebrew.yml
    - include: tasks/dotfiles.yml
    - name: Change default shell to fish 
      become: True
      user: 
        name: seb
        shell: /usr/local/bin/fish
