- hosts: localhost
  vars:
    homebrew_taps:
      - Homebrew/bundle
    dotfiles_files:
      - .ackrc
      - .bin
      - .colordiffrc
      - .config
      - .gitconfig
      - .gitignore_global
      - .nvimrc
      - .tmux.conf
      - .slate.js
      - Brewfile

  tasks:
    - include_vars: secrets.yml
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/homebrew.yml
    - include: tasks/fish.yml
    - include: tasks/vim.yml
    - include: tasks/defaults.yml
    - include: tasks/dock.yml
    - include: tasks/ruby.yml
    - include: tasks/alfred.yml
    - include: tasks/flux.yml
    - include: tasks/dash.yml
    - include: tasks/services.yml
    - include: tasks/istatmenus.yml
    - include: tasks/menubar.yml
    - include: tasks/stitch_fix.yml

  handlers:
    - name: restart istat menus
      command: "killall 'iStat Menus Status'"
      ignore_errors: true
    - name: restart dock
      command: "killall Dock"
    - name: restart system ui server
      command: "killall SystemUIServer"
