- name: Turn off natural scroll direction
  command: "defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false"

- name: Holding down key will type multiple characters
  command: "defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false"

- name: Dark mode (requires logging out)
  command: "defaults write -g AppleInterfaceStyle -string Dark"

- name: Play sound when adjusting volume
  command: "defaults write -g com.apple.sound.beep.feedback -integer 1"

- name: F8 = F8 not pause/play
  command: "defaults write -g com.apple.keyboard.fnState -bool true"

- name: Expand save panel by default
  command: "defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true"

- name: 24 hour clock with date and day
  command: "defaults write com.apple.menuextra.clock 'DateFormat' -string 'EEE MMM d H:mm'"
  notify: restart system ui server

- name: Reduce motion
  command: "defaults write com.apple.universalaccess reduceMotion -bool true"
  notify: restart system ui server
