- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "https://github.com/sebastiangeiger/new-dotfiles.git"
    dest: "~/dotfiles"
    version: "ansible"
    update: no
    accept_hostkey: True
  become: no

- name: Ensure all configured dotfiles are links.
  shell: "ls -F ~/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  always_run: yes
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Remove existing dotfiles file if a replacement is being linked.
  file:
    path: "~/{{ dotfiles_files[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Link dotfiles into home folder.
  file:
    src: "~/dotfiles/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  become: no
  with_items: "{{ dotfiles_files }}"
