- name: Get userinfo
  command: "finger {{ lookup('env','USER') }}"
  register: user_info

- name: Change default shell to fish
  become: True
  user:
    name: "{{ lookup('env','USER') }}"
    shell: /usr/local/bin/fish
  when: user_info.stdout.find("/usr/local/bin/fish") == -1

- name: Write secrets.fish
  template:
    src: templates/secrets.fish.j2
    dest: ~/.config/fish/functions/secrets.fish
