
- name: Check if homebrew binary is already in place.
  stat: path=/usr/local/bin/brew
  register: homebrew_binary

- name: Make tmp folder
  file: path=/tmp/homebrew_install state=directory mode=0755
  when: homebrew_binary.stat.exists == false

- name: Download homebrew
  get_url: url=https://raw.githubusercontent.com/Homebrew/install/master/install dest=/tmp/homebrew_install
  when: homebrew_binary.stat.exists == false

- name: Install homebrew
  command: /usr/bin/ruby /tmp/homebrew_install/install
  when: homebrew_binary.stat.exists == false

- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

- name: Update list of brews
  command: "brew update"

- name: Install from Brewfile.
  command: "brew bundle chdir=~"
