- name: Move ssh/config into place
  template: src=templates/ssh_config.j2 dest=~/.ssh/config

- name: General ssh key
  user:
    name: seb
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: SSH key for github
  user:
    name: seb
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa_github
